// DF-010 contract tests: AC-DF-010.1 (contracts/prohibited-terms.v1.json validates against the meta-schema,
// and structural mistakes are rejected) and the generator hookup (Swift + Functions copy).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { DEFAULT_ROOT, loadInputs, renderOutputs, validateInputs } from '../generate.mjs';
import { readContract, readContractText } from './helpers.mjs';
import { makeRoot, readJson, removeRoot, runCli, writeJson } from './harness.mjs';

const FILE = 'contracts/prohibited-terms.v1.json';

test('AC-DF-010.1 prohibited-terms.v1.json passes the meta-schema and cross checks', () => {
  const { loaded, errors } = loadInputs(DEFAULT_ROOT);
  assert.deepEqual(errors, []);
  assert.ok(loaded.prohibitedTerms, 'input is registered');
  assert.deepEqual(validateInputs(DEFAULT_ROOT, loaded), []);
  const doc = readContract('prohibited-terms.v1.json');
  assert.equal(doc.contract, 'prohibited-terms');
  assert.equal(doc.version, 1);
  assert.equal(doc.revision, 1);
});

test('AC-DF-010.1 canonical formatting (2-space JSON, LF, one trailing newline)', () => {
  const text = readContractText('prohibited-terms.v1.json');
  assert.ok(!text.includes('\r'));
  assert.equal(text, `${JSON.stringify(JSON.parse(text), null, 2)}\n`);
});

// Each case edits a copy of the real file and expects a validation error that mentions `expect`.
const BAD = [
  ['common row without clinicalModeNote', (d) => delete d.ruleSets.common[0].clinicalModeNote, /ruleSets\/common\/0: must have required property 'clinicalModeNote'/],
  ['missing ruleSets.trainer', (d) => delete d.ruleSets.trainer, /ruleSets: must have required property 'trainer'/],
  ['unknown rule set in pathRuleSets', (d) => d.pathRuleSets[0].ruleSets.push('clinical'), /pathRuleSets\/0\/ruleSets\/2: must be equal to one of the allowed values/],
  ['causal pattern marked block', (d) => { d.causalPatterns[0].severity = 'block'; }, /causalPatterns\/0\/severity: must be equal to constant/],
  ['non-disclaimer allow entry kind', (d) => { d.allowEntries[0].kind = 'existingDisclaimerCandidate'; }, /allowEntries\/0\/kind: must be equal to one of the allowed values/],
  ['extra top-level field', (d) => { d.notes = 'x'; }, /#: must NOT have additional properties 'notes'/],
  ['absolute glob', (d) => d.allowPaths.push('/etc/**'), /allowPaths\/\d+: must match pattern/],
  ['duplicate rule id across sets', (d) => { d.ruleSets.member[0].id = 'C1-01'; }, /ruleSets\/member\/0\/id: duplicate rule id "C1-01"/],
  ['allow entry names an unknown rule', (d) => { d.allowEntries[0].rules = ['C1-99']; }, /allowEntries\/0\/rules\/0: unknown rule id "C1-99"/],
  ['regex that does not compile', (d) => { d.ruleSets.common.find((r) => r.regex).regex = ['(']; }, /regex\/0: Invalid regular expression/],
];

for (const [name, mutate, expect] of BAD) {
  test(`AC-DF-010.1 rejects: ${name}`, () => {
    const root = makeRoot();
    try {
      const doc = readJson(root, FILE);
      mutate(doc);
      writeJson(root, FILE, doc);
      const r = runCli(['--root', root, '--check']);
      assert.equal(r.code, 1);
      assert.match(r.stderr, expect);
    } finally {
      removeRoot(root);
    }
  });
}

test('DF-010 generator: Functions copy is verbatim and the Swift file lists every rule', () => {
  const { loaded } = loadInputs(DEFAULT_ROOT);
  const { outputs } = renderOutputs(loaded);
  const doc = readContract('prohibited-terms.v1.json');
  assert.equal(outputs.get('functions/src/shared/generated/json/prohibited-terms.v1.json'), readContractText('prohibited-terms.v1.json'));
  const swift = outputs.get('trainer_app/Packages/TrainerCore/Sources/TrainerContracts/Generated/ProhibitedTerms.swift');
  assert.ok(swift.startsWith('// GENERATED by tool/contracts/generate.mjs from contracts/prohibited-terms.v1.json — DO NOT EDIT. sha256:'));
  assert.ok(!/^import /m.test(swift), 'TrainerContracts stays free of imports (pure target)');
  const ids = [...swift.matchAll(/^ {6}id: "([^"]+)",$/gm)].map((m) => m[1]);
  assert.deepEqual(ids, [...doc.ruleSets.common, ...doc.ruleSets.member, ...doc.ruleSets.trainer].map((r) => r.id));
  assert.ok(swift.includes('  public static let trainerAbbreviations: [String] = ["SOAP", "ROM", "AROM", "PROM", "MMT", "NRS", "MDC"]'));
  assert.ok(swift.includes('  public static let trainer: [TermRule] = []'));
  assert.ok(swift.includes('regex: ["정확도\\\\s*:?\\\\s*\\\\d+(\\\\.\\\\d+)?\\\\s*%"],'), 'backslashes are escaped in Swift literals');
  assert.ok(swift.includes('onlyInGlobs: ["trainer_app/Packages/TrainerKit/Sources/FeatureLidarBeta/**", "trainer_app/Packages/TrainerKit/Sources/BodyPath*/**"]'));
  // Inactive allow entries are left out of the app.
  const root = makeRoot();
  try {
    const d = readJson(root, FILE);
    d.allowEntries[1].active = false;
    writeJson(root, FILE, d);
    assert.equal(runCli(['--root', root]).code, 0);
    const text = readFileSync(path.join(root, 'trainer_app/Packages/TrainerCore/Sources/TrainerContracts/Generated/ProhibitedTerms.swift'), 'utf8');
    assert.ok(text.includes('TermAllowEntry(id: "AE-01"'));
    assert.ok(!text.includes('TermAllowEntry(id: "AE-02"'));
  } finally {
    removeRoot(root);
  }
});
