// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// DF-043: storageBucket pins the Seoul bucket (DEC-19). Re-apply after `flutterfire configure`.
import 'config/storage_bucket.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTrKQbkqt1nTw4M64sygpK-J4aTegO3I',
    appId: '1:1011088994661:android:7b256f3f8c19223d5df18c',
    messagingSenderId: '1011088994661',
    projectId: 'dfetmanage',
    storageBucket: seoulStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYdNFAGfCfexw-r89mGnzELFEvx0Hu-A',
    appId: '1:1011088994661:ios:58e7f0262c084e555df18c',
    messagingSenderId: '1011088994661',
    projectId: 'dfetmanage',
    storageBucket: seoulStorageBucket,
    androidClientId:
        '1011088994661-fajhfegjbdd39hnk71mqi9074rqjcjvo.apps.googleusercontent.com',
    iosClientId:
        '1011088994661-evig73mi1ou4eke97df4os1ah4bpu889.apps.googleusercontent.com',
    iosBundleId: 'kr.co.dfet.coach',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChn4MfHoqcxMKCkW49Oop3afe2wS8iK1M',
    appId: '1:1011088994661:web:b53b172998bea9c85df18c',
    messagingSenderId: '1011088994661',
    projectId: 'dfetmanage',
    authDomain: 'dfetmanage.firebaseapp.com',
    storageBucket: seoulStorageBucket,
  );
}
