// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTrKQbkqt1nTw4M64sygpK-J4aTegO3I',
    appId: '1:1011088994661:android:8ec1270399fb3bb35df18c',
    messagingSenderId: '1011088994661',
    projectId: 'dfetmanage',
    storageBucket: 'dfetmanage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYdNFAGfCfexw-r89mGnzELFEvx0Hu-A',
    appId: '1:1011088994661:ios:fee8b625c9902bfa5df18c',
    messagingSenderId: '1011088994661',
    projectId: 'dfetmanage',
    storageBucket: 'dfetmanage.firebasestorage.app',
    androidClientId: '1011088994661-fajhfegjbdd39hnk71mqi9074rqjcjvo.apps.googleusercontent.com',
    iosClientId: '1011088994661-evig73mi1ou4eke97df4os1ah4bpu889.apps.googleusercontent.com',
    iosBundleId: 'com.example.dfetCoach',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiTrKQbkqt1nTw4M64sygpK-J4aTegO3I',
    appId: '1:1011088994661:web:abc123def456ghi789jkl',
    messagingSenderId: '1011088994661',
    projectId: 'dfetmanage',
    authDomain: 'dfetmanage.firebaseapp.com',
    storageBucket: 'dfetmanage.firebasestorage.app',
  );

}