#!/usr/bin/env node
// contracts generator (DF-004, ADR-005).
//
//   node tool/contracts/generate.mjs            validate contracts/*.json and (re)write the generated files
//   node tool/contracts/generate.mjs --check    validate, then compare the generated files on disk; exit 1 on drift
//   options: --root <dir>  repository root to operate on (default: this checkout; tests use a temp copy)
//
// Order of work: 1) ajv validation against schemas/contracts-meta.schema.json (JSON Schema 2020-12),
// 2) cross checks between the files (duplicate metricCode, excluded codes, vocab membership, ...),
// 3) render every output in memory, 4) write or --check. Output is deterministic: input order is
// preserved, LF line endings, 2-space indentation, and the first line of every file is
//   <comment> GENERATED by tool/contracts/generate.mjs from contracts/<file> — DO NOT EDIT. sha256:<12 hex>
// where the hash covers the bytes of the listed input file(s), concatenated in the listed order.
// The json/ copies for Functions are verbatim (JSON has no comments) and carry no header.
//
// Exit codes: 0 ok, 1 validation error or drift, 2 usage or internal error.
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import Ajv2020Module from 'ajv/dist/2020.js';
import addFormatsModule from 'ajv-formats';

import { FEATURE_FLAG_KEY_MEMBERS, METRIC_FIELD_ENUMS, RESERVED_TYPE_NAMES, typeName } from './emitters/common.mjs';
import { SWIFT_DIR, swiftEmitters, swiftIdentCollisions } from './emitters/swift.mjs';
import { DART_DIR, dartEmitters, dartIdent, dartIdentCollisions } from './emitters/dart.mjs';
import { FUNCTIONS_DIR, functionsEmitters } from './emitters/functions.mjs';
import { ADMIN_WEB_DIR, adminWebEmitters } from './emitters/adminWeb.mjs';
import { schemasEmitters } from './emitters/schemas.mjs';

const Ajv2020 = Ajv2020Module.default ?? Ajv2020Module;
const addFormats = addFormatsModule.default ?? addFormatsModule;

export const DEFAULT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const META_SCHEMA = 'schemas/contracts-meta.schema.json';
export const GENERATOR = 'tool/contracts/generate.mjs';

// Input registry. A missing file is skipped with a warning, together with every emitter that needs it.
// Later stories append inputs and emitters: DF-033 analytics-events and audit-actions. contracts/fixtures/** is never copied (DF-009 reads it in place).
export const INPUTS = [
  {
    file: 'metric-catalog.v1.json',
    key: 'metricCatalog',
    requires: ['vocab'],
    emit: [swiftEmitters.metricCatalog, dartEmitters.metricCatalog, functionsEmitters.metricCatalogJson],
  },
  {
    file: 'vocab.v1.json',
    key: 'vocab',
    requires: [],
    emit: [swiftEmitters.vocab, dartEmitters.vocab, functionsEmitters.vocabJson],
  },
  {
    // DF-010: PRD appendix C. Swift for the trainer app's inline warnings (DF-120), a verbatim copy for
    // Functions (DF-309). The copy-lint tool reads contracts/ directly. No Dart or admin_web output.
    file: 'prohibited-terms.v1.json',
    key: 'prohibitedTerms',
    requires: [],
    emit: [swiftEmitters.prohibitedTerms, functionsEmitters.prohibitedTermsJson],
  },
  {
    // DF-027: appConfig/features keys (ADR-010). Swift FeatureFlagKey for TrainerDomain FeatureFlags, Dart
    // FeatureFlagKey for AppFeatureFlags, the example document in schemas/, and FEATURE_FLAGS in admin_web
    // contracts.ts (aggregate below). tool/contracts/test/flags-rules.test.mjs checks featureOn() keys in the rules.
    file: 'feature-flags.v1.json',
    key: 'featureFlags',
    requires: [],
    emit: [swiftEmitters.featureFlags, dartEmitters.featureFlags, schemasEmitters.featureFlagsExample],
  },
];

// Outputs built from more than one input. `partial: true` renders with whichever inputs are present.
export const AGGREGATES = [
  swiftEmitters.contractsVersion,
  dartEmitters.contractsVersion,
  functionsEmitters.contracts,
  adminWebEmitters.contracts,
];

// Directories owned entirely by the generator. Files in them that the generator does not produce
// are drift (--check) or are removed (write mode).
export const GENERATED_DIRS = [SWIFT_DIR, DART_DIR, FUNCTIONS_DIR, ADMIN_WEB_DIR];

const sha256 = (data) => createHash('sha256').update(data).digest('hex');

export function headerLine(comment, files, hash12) {
  const from = files.map((f) => `contracts/${f}`).join(', ');
  return `${comment} GENERATED by ${GENERATOR} from ${from} — DO NOT EDIT. sha256:${hash12}`;
}

// ---------------------------------------------------------------------------------------------
// 1. Load

export function loadInputs(root) {
  const loaded = {};
  const warnings = [];
  const errors = [];
  for (const input of INPUTS) {
    const abs = path.join(root, 'contracts', input.file);
    if (!existsSync(abs)) {
      warnings.push(`contracts/${input.file} not found; skipping its outputs`);
      continue;
    }
    const buf = readFileSync(abs);
    const text = buf.toString('utf8');
    let doc;
    try {
      doc = JSON.parse(text);
    } catch (err) {
      errors.push(`contracts/${input.file}: invalid JSON: ${err.message}`);
      continue;
    }
    const hash = sha256(buf);
    loaded[input.key] = { ...input, doc, text, buf, sha256: hash, sha12: hash.slice(0, 12) };
  }
  for (const input of INPUTS) {
    if (!loaded[input.key]) continue;
    const missing = input.requires.filter((k) => !loaded[k]);
    if (missing.length) {
      warnings.push(`contracts/${input.file} needs ${missing.join(', ')}; skipping its outputs`);
      delete loaded[input.key];
    }
  }
  return { loaded, warnings, errors };
}

// ---------------------------------------------------------------------------------------------
// 2. Validate: meta-schema first, then cross checks

export function compileMetaSchema(root) {
  const schema = JSON.parse(readFileSync(path.join(root, META_SCHEMA), 'utf8'));
  // strictTypes/strictRequired are off because if/then branches legitimately omit `type`.
  const ajv = new Ajv2020({ allErrors: true, strict: true, strictTypes: false, strictRequired: false });
  addFormats(ajv);
  return ajv.compile(schema);
}

function formatAjvError(file, e) {
  let detail = '';
  if (e.keyword === 'additionalProperties') detail = ` '${e.params.additionalProperty}'`;
  else if (e.keyword === 'enum' || e.keyword === 'const') detail = ` ${JSON.stringify(e.params.allowedValues ?? e.params.allowedValue)}`;
  return `contracts/${file}#${e.instancePath}: ${e.message}${detail}`;
}

export function schemaErrors(validate, input) {
  if (validate(input.doc)) return [];
  // if/then/else wrappers only repeat the nested error.
  const errs = validate.errors.filter((e) => e.keyword !== 'if');
  return [...new Set(errs.map((e) => formatAjvError(input.file, e)))];
}

// Generated identifiers must stay unique per enum after each language's escaping.
// `pointer(index)` gives the JSON pointer of the value at that index.
function identifierErrors(values, pointer, { vocab }) {
  const errors = [];
  for (const c of dartIdentCollisions(values)) {
    errors.push(`${pointer(c.index)}: Dart identifier ${c.ident} for "${c.value}" collides with "${c.other}"`);
  }
  for (const c of swiftIdentCollisions(values, { vocab })) {
    errors.push(`${pointer(c.index)}: Swift case ${c.ident} for "${c.value}" collides with ${c.other.startsWith('generated') ? c.other : `"${c.other}"`}`);
  }
  return errors;
}

export function crossCheckErrors(loaded) {
  const errors = [];
  const vocab = loaded.vocab?.doc;
  if (vocab) {
    const v = `contracts/${loaded.vocab.file}`;
    for (const [key, entry] of Object.entries(vocab.enums)) {
      const tn = typeName(key);
      if (RESERVED_TYPE_NAMES.includes(tn)) {
        errors.push(`${v}#/enums/${key}: enum type name ${tn} collides with a generated type`);
      }
      if (entry.labelsKo) {
        const labelKeys = Object.keys(entry.labelsKo);
        const extra = labelKeys.filter((k) => !entry.values.includes(k));
        const missing = entry.values.filter((k) => !labelKeys.includes(k));
        if (extra.length) errors.push(`${v}#/enums/${key}/labelsKo: labels for unknown values ${extra.join(', ')}`);
        if (missing.length) errors.push(`${v}#/enums/${key}/labelsKo: missing labels for ${missing.join(', ')}`);
      }
      errors.push(...identifierErrors(entry.values, (i) => `${v}#/enums/${key}/values/${i}`, { vocab: true }));
    }
    const typeNames = new Map();
    for (const key of Object.keys(vocab.enums)) {
      const tn = typeName(key);
      if (typeNames.has(tn)) errors.push(`${v}#/enums/${key}: type name ${tn} also used by ${typeNames.get(tn)}`);
      typeNames.set(tn, key);
    }
    const joints = vocab.enums.joint?.values ?? [];
    const motions = vocab.enums.motion?.values ?? [];
    vocab.jointMotionPairs.pairs.forEach((p, i) => {
      const at = `${v}#/jointMotionPairs/pairs/${i}`;
      if (!joints.includes(p.joint)) errors.push(`${at}/joint: "${p.joint}" is not in vocab joint`);
      p.motions.forEach((m, j) => {
        if (!motions.includes(m)) errors.push(`${at}/motions/${j}: "${m}" is not in vocab motion`);
      });
    });
  }

  const catalog = loaded.metricCatalog?.doc;
  if (catalog && vocab) {
    const c = `contracts/${loaded.metricCatalog.file}`;
    const firstIndex = new Map();
    const codes = new Set(catalog.metrics.map((m) => m.metricCode));
    errors.push(...identifierErrors(catalog.metrics.map((m) => m.metricCode), (i) => `${c}#/metrics/${i}/metricCode`, { vocab: false }));
    catalog.metrics.forEach((m, i) => {
      const at = `${c}#/metrics/${i}`;
      if (firstIndex.has(m.metricCode)) {
        errors.push(`${at}/metricCode: duplicate metricCode "${m.metricCode}" (first at #/metrics/${firstIndex.get(m.metricCode)})`);
      } else {
        firstIndex.set(m.metricCode, i);
      }
      if (catalog.excludedMetricCodes.includes(m.metricCode)) {
        errors.push(`${at}/metricCode: "${m.metricCode}" is listed in excludedMetricCodes`);
      }
      for (const [field, enumKey] of Object.entries(METRIC_FIELD_ENUMS)) {
        const allowed = vocab.enums[enumKey]?.values;
        if (!allowed) {
          errors.push(`${at}/${field}: vocab has no enum "${enumKey}"`);
          continue;
        }
        const value = m[field];
        if (value === null) continue; // reliabilityTier may be null (schema enforces where)
        const list = Array.isArray(value) ? value : [value];
        list.forEach((item, j) => {
          if (!allowed.includes(item)) {
            const ptr = Array.isArray(value) ? `${at}/${field}/${j}` : `${at}/${field}`;
            errors.push(`${ptr}: "${item}" is not in vocab ${enumKey}`);
          }
        });
      }
      for (const subset of ['screeningOnlySourceGrades', 'betaSourceGrades']) {
        m[subset].forEach((g, j) => {
          if (!m.allowedSourceGrades.includes(g)) {
            errors.push(`${at}/${subset}/${j}: "${g}" is not in allowedSourceGrades`);
          }
        });
      }
      if (m.judgeAs !== null && (!codes.has(m.judgeAs) || m.judgeAs === m.metricCode)) {
        errors.push(`${at}/judgeAs: "${m.judgeAs}" must be another metricCode in this catalog`);
      }
      if (m.range && m.range.min > m.range.max) {
        errors.push(`${at}/range: min ${m.range.min} is greater than max ${m.range.max}`);
      } else if (m.range && (m.range.appMin < m.range.min || m.range.appMin > m.range.max)) {
        errors.push(`${at}/range/appMin: ${m.range.appMin} is outside [${m.range.min}, ${m.range.max}]`);
      }
    });
  }
  const terms = loaded.prohibitedTerms?.doc;
  if (terms) errors.push(...prohibitedTermsErrors(`contracts/${loaded.prohibitedTerms.file}`, terms));
  const flags = loaded.featureFlags?.doc;
  if (flags) errors.push(...featureFlagErrors(`contracts/${loaded.featureFlags.file}`, flags));
  return errors;
}

// DF-027: keys unique, not a member name of the generated enums, and unique after Dart/Swift escaping.
function featureFlagErrors(p, doc) {
  const errors = [];
  const firstIndex = new Map();
  doc.flags.forEach((f, i) => {
    if (firstIndex.has(f.key)) errors.push(`${p}#/flags/${i}/key: duplicate key "${f.key}" (first at #/flags/${firstIndex.get(f.key)})`);
    else firstIndex.set(f.key, i);
    // Checked before and after Dart escaping: `default` becomes `defaultValue` in Dart.
    const member = [f.key, dartIdent(f.key)].find((ident) => FEATURE_FLAG_KEY_MEMBERS.includes(ident));
    if (member) errors.push(`${p}#/flags/${i}/key: "${f.key}" collides with the generated FeatureFlagKey member ${member}`);
  });
  errors.push(...identifierErrors(doc.flags.map((f) => f.key), (i) => `${p}#/flags/${i}/key`, { vocab: false }));
  return errors;
}

// DF-010: rule ids unique across sets, allow entries point at existing rules, every pattern compiles
// with the flags the matchers use (docs/v1/12 §7.3).
function prohibitedTermsErrors(p, doc) {
  const errors = [];
  const seen = new Map();
  for (const [set, rules] of Object.entries(doc.ruleSets)) {
    rules.forEach((r, i) => {
      const at = `${p}#/ruleSets/${set}/${i}`;
      if (seen.has(r.id)) errors.push(`${at}/id: duplicate rule id "${r.id}" (first at ${seen.get(r.id)})`);
      else seen.set(r.id, `#/ruleSets/${set}/${i}`);
      (r.regex ?? []).forEach((rx, j) => {
        try {
          new RegExp(rx, 'giu');
        } catch (e) {
          errors.push(`${at}/regex/${j}: ${e.message}`);
        }
      });
    });
  }
  doc.causalPatterns.forEach((c, i) => {
    try {
      new RegExp(c.regex, 'gu');
    } catch (e) {
      errors.push(`${p}#/causalPatterns/${i}/regex: ${e.message}`);
    }
  });
  doc.allowEntries.forEach((e, i) => {
    e.rules.forEach((id, j) => {
      if (!seen.has(id)) errors.push(`${p}#/allowEntries/${i}/rules/${j}: unknown rule id "${id}"`);
    });
  });
  return errors;
}

export function validateInputs(root, loaded) {
  const validate = compileMetaSchema(root);
  const errors = [];
  for (const input of Object.values(loaded)) errors.push(...schemaErrors(validate, input));
  // Cross checks assume the structure is valid, so they run only after the meta-schema passes.
  if (errors.length === 0) errors.push(...crossCheckErrors(loaded));
  return errors;
}

// ---------------------------------------------------------------------------------------------
// 3. Render

function resolvePath(emitter, loaded) {
  return typeof emitter.path === 'function' ? emitter.path(loaded) : emitter.path;
}

function renderOne(emitter, loaded) {
  const present = emitter.uses.filter((k) => loaded[k]).map((k) => loaded[k]);
  if (present.length === 0) return null;
  if (present.length < emitter.uses.length && !emitter.partial) return null;
  const ctx = { ...loaded, present };
  const body = emitter.render(ctx);
  if (emitter.comment === null) return body;
  const hash = present.length === 1 ? present[0].sha256 : sha256(Buffer.concat(present.map((p) => p.buf)));
  return `${headerLine(emitter.comment, present.map((p) => p.file), hash.slice(0, 12))}\n${body}`;
}

// Returns Map<relativePath, content> in a stable order, plus warnings for skipped emitters.
export function renderOutputs(loaded) {
  const outputs = new Map();
  const warnings = [];
  const emitters = [...INPUTS.flatMap((i) => i.emit), ...AGGREGATES];
  for (const emitter of emitters) {
    const content = renderOne(emitter, loaded);
    if (content === null) {
      if (emitter.uses.some((k) => loaded[k])) warnings.push(`${emitter.id} skipped: needs ${emitter.uses.join(', ')}`);
      continue;
    }
    const rel = resolvePath(emitter, loaded);
    if (outputs.has(rel)) throw new Error(`two emitters write ${rel}`);
    if (content.includes('\r')) throw new Error(`${rel}: CR in output`);
    outputs.set(rel, content);
  }
  return { outputs, warnings };
}

// ---------------------------------------------------------------------------------------------
// 4. Write / check

function listFiles(root, dir) {
  const abs = path.join(root, dir);
  if (!existsSync(abs)) return [];
  const found = [];
  for (const ent of readdirSync(abs, { withFileTypes: true, recursive: true })) {
    if (!ent.isFile() || ent.name.startsWith('.')) continue;
    const parent = ent.parentPath ?? ent.path;
    found.push(path.relative(root, path.join(parent, ent.name)).split(path.sep).join('/'));
  }
  return found.sort();
}

export function diffOutputs(root, outputs) {
  const drift = [];
  for (const [rel, content] of outputs) {
    const abs = path.join(root, rel);
    if (!existsSync(abs)) drift.push({ path: rel, kind: 'missing' });
    else if (!readFileSync(abs).equals(Buffer.from(content, 'utf8'))) drift.push({ path: rel, kind: 'modified' });
  }
  for (const dir of GENERATED_DIRS) {
    for (const rel of listFiles(root, dir)) {
      if (!outputs.has(rel)) drift.push({ path: rel, kind: 'unexpected' });
    }
  }
  return drift;
}

export function run({ root = DEFAULT_ROOT, check = false, out = console.log, err = console.error } = {}) {
  const { loaded, warnings, errors: loadErrors } = loadInputs(root);
  for (const w of warnings) err(`warning: ${w}`);
  if (loadErrors.length) {
    for (const e of loadErrors) err(`error: ${e}`);
    return 1;
  }
  const errors = validateInputs(root, loaded);
  if (errors.length) {
    err(`contracts: ${errors.length} validation error(s) (${META_SCHEMA} and cross checks):`);
    for (const e of errors) err(`  ${e}`);
    return 1;
  }
  const { outputs, warnings: renderWarnings } = renderOutputs(loaded);
  for (const w of renderWarnings) err(`warning: ${w}`);
  const drift = diffOutputs(root, outputs);

  if (check) {
    if (drift.length === 0) {
      out(`contracts: ${outputs.size} generated files are up to date`);
      return 0;
    }
    err(`contracts: ${drift.length} generated file(s) differ from ${GENERATOR} output:`);
    for (const d of drift) err(`  ${d.kind.padEnd(10)} ${d.path}`);
    err(`Do not edit generated files. Run: node ${GENERATOR} and commit the result.`);
    return 1;
  }

  for (const d of drift) {
    const abs = path.join(root, d.path);
    if (d.kind === 'unexpected') {
      rmSync(abs);
    } else {
      mkdirSync(path.dirname(abs), { recursive: true });
      writeFileSync(abs, outputs.get(d.path));
    }
    out(`${d.kind === 'unexpected' ? 'removed' : 'wrote'}  ${d.path}`);
  }
  out(`contracts: ${outputs.size} generated files, ${drift.length} changed`);
  return 0;
}

class UsageError extends Error {}

function parseArgs(argv) {
  const opts = { check: false, root: DEFAULT_ROOT };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--check') opts.check = true;
    else if (a === '--root') {
      const dir = argv[++i];
      if (dir === undefined || dir === '' || dir.startsWith('--')) throw new UsageError('--root needs a directory');
      opts.root = path.resolve(dir);
    }
    else if (a === '-h' || a === '--help') opts.help = true;
    else throw new UsageError(`unknown argument ${a}`);
  }
  return opts;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  let code;
  try {
    const opts = parseArgs(process.argv.slice(2));
    if (opts.help) {
      console.log('usage: node tool/contracts/generate.mjs [--check] [--root <dir>]');
      code = 0;
    } else {
      code = run(opts);
    }
  } catch (e) {
    if (e instanceof UsageError) console.error(`contracts: ${e.message}\nusage: node tool/contracts/generate.mjs [--check] [--root <dir>]`);
    else console.error(`contracts: ${e.stack ?? e}`);
    code = 2;
  }
  process.exitCode = code;
}
